#docker-compose.yml
version: '3'
services:
  node-app:
    build: .
    container_name: app1
    ports:
      - "3500:3500"
    #Production==========
    #Development=========
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3500
    #env_file:
    # - ./.env
  mongodb-node:
    image: mongo
    container_name: mongo1
    restart: unless-stopped
    ports:
      - 27037:27017
    # - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=super-password1
    volumes:
      - mongo1db:/data/db

volumes:
  mongo1db:


