#docker-compose.yml
version: '3'
services:
  node-app:
    build: .
    ports:
      - "3500:3500"
    #Production==========
    #Development=========
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3500
    #env_file:
    # - ./.env
    depends_on:
      - mysqldb
    networks:
      - internalnet

  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - mysql-db:/var/lib/mysql
    #local folder
    #  - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: super-password1
      MYSQL_ROOT_PASSWORD: super-password1
      SERVICE_TAGS: prodcd ..
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge

volumes:
  mysql-db:
