#docker-compose.yml
version: '3'
services:
  node-app:
    build: .
    ports:
      - "3500:3500"
    #Production==========
    #Development=========
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      - PORT=3500
    #env_file:
    # - ./.env

