//request.rest
###  0. GET String
GET http://localhost:3500/

###  0. GET Connected
GET http://localhost:3500/coba

###  1. GET Data Pasien
GET http://localhost:3500/dtpasien

###  2. GET Data Pasien by ID
GET http://localhost:3500/dtpasien/2

###  3. CREATE Data Pasien
POST http://localhost:3500/dtpasien
content-type: application/json

{
  "id" : 13,
  "nama" : "Edy5",
  "alamat" : "Semarang"
}

###  3. DELETE Data Pasien
DELETE  http://localhost:3500/dtpasien/13

###  3. UPDATE Data Pasien
PUT  http://localhost:3500/dtpasien/12
content-type: application/json

{
  "nama" : "Edy UPDATE",
  "alamat" : "Semarang UPDATE"
}